import { useState } from 'react'
import type { FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { sendJson } from '../../services/apiClient'

export function ForgotPasswordPage() {
  const navigate = useNavigate(); const [step, setStep] = useState(1); const [email, setEmail] = useState(''); const [otp, setOtp] = useState(''); const [newPassword, setNewPassword] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const requestOtp = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await sendJson('/users/send-reset-otp', 'POST', { email }); setMessage('If an account exists, a verification code has been sent to your email.'); setStep(2) } catch (reason) { setError((reason as Error).message) } finally { setBusy(false) } }
  const verifyOtp = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await sendJson('/users/verify-reset-otp', 'POST', { email, otp }); setStep(3); setMessage('Code verified. Choose a new password.') } catch (reason) { setError((reason as Error).message) } finally { setBusy(false) } }
  const resetPassword = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await sendJson('/users/reset-password', 'POST', { email, otp, newPassword }); setMessage('Password reset successfully. You can sign in now.'); setTimeout(() => navigate('/login'), 900) } catch (reason) { setError((reason as Error).message) } finally { setBusy(false) } }
  return <main className="auth-page section"><div className="auth-card"><span className="eyebrow">Account recovery · Step {step} of 3</span><h1>Get back into your account.</h1><p>{message || 'We will send a one-time code to verify your email.'}</p>{step === 1 && <form className="auth-form" onSubmit={requestOtp}><label>Email<input type="email" required value={email} onChange={(event) => setEmail(event.target.value)} /></label><button className="primary-button" disabled={busy}>{busy ? 'Sending...' : 'Send recovery code'} <span>↗</span></button></form>}{step === 2 && <form className="auth-form" onSubmit={verifyOtp}><label>Verification code<input inputMode="numeric" required minLength={6} maxLength={6} value={otp} onChange={(event) => setOtp(event.target.value)} /></label><button className="primary-button" disabled={busy}>{busy ? 'Checking...' : 'Verify code'} <span>↗</span></button><button type="button" className="link-button" onClick={() => setStep(1)}>Use another email</button></form>}{step === 3 && <form className="auth-form" onSubmit={resetPassword}><label>New password<input type="password" required minLength={6} value={newPassword} onChange={(event) => setNewPassword(event.target.value)} /></label><button className="primary-button" disabled={busy}>{busy ? 'Updating...' : 'Reset password'} <span>↗</span></button></form>}{error && <div className="form-error">{error}</div>}<small><Link to="/login">Back to sign in</Link></small></div></main>
}
