export type ImageRef = { url?: string }
export type Product = { _id: string; name: string; brand?: string; description?: string; finalPrice?: number | string | { $numberDecimal?: string }; price?: number | string | { $numberDecimal?: string }; discountPercentage?: number; ratings?: number; reviews?: number; images?: ImageRef[]; coverImage?: ImageRef; stock?: number; badges?: string[] }
export type Category = { _id: string; name: string; slug: string; image?: ImageRef; description?: string }
export type Banner = { _id: string; title?: string; tagline?: string; image?: ImageRef; redirectLink?: string }
export type ProductList = { products: Product[]; total: number; page: number; totalPages: number }
export type Cart = { items: Array<{ _id: string; quantity: number; unitPriceSnapshot?: Product['price']; lineTotalSnapshot?: Product['price']; product?: Product }>; totalItems: number; subtotal: Product['price']; discountAmount: Product['price']; finalAmount: Product['price'] }
export type Address = { label: string; street: string; city: string; state: string; pincode: string; country?: string; isDefault?: boolean }
export type AuthUser = { _id: string; fullname?: string; username?: string; email: string; phone?: string; role: string; avatar?: string; addresses?: Address[] }
export type Wishlist = { items: Array<{ _id: string; product?: Product; isAvailable?: boolean }> }
export type OrderItem = { _id: string; product?: { name?: string; image?: string; slug?: string }; quantity?: number; lineTotal?: Product['price']; fulfillmentStatus?: string; returnStatus?: string; refundStatus?: string }
export type OrderSummary = { _id: string; orderStatus: string; paymentStatus: string; finalAmount: Product['price']; createdAt: string; items?: OrderItem[] }
export type OrderDetail = OrderSummary & { shippingAddress?: Address; subtotal?: Product['price']; discount?: Product['price']; paymentMethod?: string; statusHistory?: Array<{ status: string; updatedAt?: string }>; items?: OrderItem[] }
export type Review = { _id: string; rating: number; title?: string; comment?: string; isVerifiedPurchase?: boolean; createdAt?: string; user?: { fullname?: string; username?: string; avatar?: string }; sellerResponse?: { message?: string } }
export type ProductQuestion = { _id: string; question: string; answer?: string; status: string; createdAt?: string; user?: { fullname?: string; username?: string }; answeredBy?: { fullname?: string; username?: string } }
export type Notification = { _id: string; title: string; message: string; category: string; event: string; priority?: string; isRead: boolean; createdAt: string; relatedEntity?: { entityType?: string; entityId?: string } }
