import { API_BASE } from './constants'

function headers(): Record<string, string> { const token = sessionStorage.getItem('smartcart.accessToken'); return token ? { Authorization: `Bearer ${token}` } : {} }
const shouldRefresh = (path: string) => !['/users/login', '/users/refresh-token', '/users/send-reset-otp', '/users/verify-reset-otp', '/users/reset-password'].some((item) => path.startsWith(item))
let refreshPromise: Promise<boolean> | null = null
async function refreshAccessToken() { if (!refreshPromise) refreshPromise = fetch(`${API_BASE}/users/refresh-token`, { method: 'POST', credentials: 'include' }).then(async (response) => { if (!response.ok) return false; const body = await response.json(); const token = body.data?.accessToken; if (!token) return false; sessionStorage.setItem('smartcart.accessToken', token); return true }).catch(() => false).finally(() => { refreshPromise = null }); return refreshPromise }
async function request(path: string, init: RequestInit, retry = true): Promise<Response> { const response = await fetch(`${API_BASE}${path}`, { ...init, credentials: 'include', headers: { ...headers(), ...(init.headers || {}) } }); if (response.status === 401 && retry && shouldRefresh(path) && await refreshAccessToken()) return request(path, init, false); return response }
async function responseBody<T>(response: Response, fallback: string): Promise<T> { const body = await response.json(); if (!response.ok || body.success === false) throw new Error(body.message || fallback); return (body.data ?? body) as T }
export async function getJson<T>(path: string): Promise<T> { return responseBody<T>(await request(path, {}), 'Unable to load SmartCart data') }
export async function sendJson<T>(path: string, method: string, payload?: unknown): Promise<T> { return responseBody<T>(await request(path, { method, headers: { 'Content-Type': 'application/json' }, body: payload ? JSON.stringify(payload) : undefined }), 'Request could not be completed') }
export async function sendForm<T>(path: string, formData: FormData, method = 'POST'): Promise<T> { return responseBody<T>(await request(path, { method, body: formData }), 'Request could not be completed') }
export async function getBlob(path: string) { const response = await request(path, {}); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.message || 'Download failed') }; return response.blob() }
