import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../features/auth/AuthProvider'
import { getJson, sendJson } from '../shared/api'
import type { Cart } from '../shared/types'
import { formatPrice, productImage } from '../shared/formatters'
import { SimpleAccountPage } from './SimpleAccountPage'

export function CartPage() {
  const { user } = useAuth(); const [cart, setCart] = useState<Cart | null>(null); const [coupon, setCoupon] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState('')
  const refresh = () => getJson<Cart>('/carts').then(setCart).catch((error: Error) => setMessage(error.message)).finally(() => setLoading(false))
  useEffect(() => { if (user) refresh(); else setLoading(false) }, [user])
  const updateQuantity = async (itemId: string, quantity: number) => { setBusy(itemId); try { setCart(await sendJson<Cart>(`/carts/update/${itemId}`, 'PUT', { quantity })) } catch (error) { setMessage((error as Error).message) } finally { setBusy('') } }
  const removeItem = async (itemId: string) => { setBusy(itemId); try { setCart(await sendJson<Cart>(`/carts/remove/${itemId}`, 'DELETE')) } catch (error) { setMessage((error as Error).message) } finally { setBusy('') } }
  const clear = async () => { setBusy('clear'); try { setCart(await sendJson<Cart>('/carts/clear', 'DELETE')) } catch (error) { setMessage((error as Error).message) } finally { setBusy('') } }
  const applyCoupon = async (event: React.FormEvent) => { event.preventDefault(); if (!coupon.trim()) return; setBusy('coupon'); setMessage(''); try { setCart(await sendJson<Cart>('/carts/apply-coupon', 'POST', { couponCode: coupon.trim() })); setMessage('Coupon applied successfully.') } catch (error) { setMessage((error as Error).message) } finally { setBusy('') } }
  if (!user) return <SimpleAccountPage title="Your bag is private." text="Sign in to see your saved bag and continue checkout." link="/login" linkText="Sign in" />
  if (loading) return <main className="section empty-page"><h1>Loading your bag...</h1></main>
  return <main className="cart-page section"><div className="catalog-heading"><div><span className="eyebrow">Your edit</span><h1>Your bag</h1></div>{cart?.items?.length ? <button className="link-button" onClick={clear} disabled={!!busy}>Clear bag</button> : null}</div>{message && <div className="api-notice">{message}</div>}{cart?.items?.length ? <div className="cart-layout"><div>{cart.items.map((item) => <div className="cart-item" key={item._id}><img src={productImage(item.product || { _id: '', name: '' })} alt={item.product?.name || 'Product'} /><div className="cart-item__info"><span className="eyebrow">{item.product?.brand || 'SmartCart'}</span><h3>{item.product?.name || 'Product'}</h3><strong>{formatPrice(item.lineTotalSnapshot || item.unitPriceSnapshot)}</strong><div className="quantity"><button disabled={!!busy} onClick={() => updateQuantity(item._id, Math.max(1, item.quantity - 1))}>-</button><span>{item.quantity}</span><button disabled={!!busy} onClick={() => updateQuantity(item._id, item.quantity + 1)}>+</button></div><button className="link-button cart-remove" disabled={!!busy} onClick={() => removeItem(item._id)}>Remove</button></div></div>)}</div><aside className="cart-summary"><span className="eyebrow">Order summary</span><h2>{formatPrice(cart.finalAmount)}</h2><p>Subtotal <b>{formatPrice(cart.subtotal)}</b></p><p>Discount <b>-{formatPrice(cart.discountAmount)}</b></p><form className="cart-coupon" onSubmit={applyCoupon}><input placeholder="Coupon code" value={coupon} onChange={(event) => setCoupon(event.target.value)} /><button className="ghost-dark-button" disabled={!!busy}>{busy === 'coupon' ? '...' : 'Apply'}</button></form><Link className="primary-button" to="/checkout">Continue to checkout <span>↗</span></Link></aside></div> : <div className="empty-page"><h1>Your bag is waiting.</h1><p>Add something considered to get started.</p><Link className="primary-button" to="/products">Explore products</Link></div>}</main>
}
