import { useEffect, useState } from 'react'
import { Link, useLocation, useParams } from 'react-router-dom'
import { useAuth } from '../features/auth/AuthProvider'
import { getBlob, getJson, sendJson } from '../shared/api'
import type { OrderDetail, OrderSummary } from '../shared/types'
import { formatPrice } from '../shared/formatters'
import { SimpleAccountPage } from './SimpleAccountPage'

export function OrdersPage() {
  const { user } = useAuth(); const [orders, setOrders] = useState<OrderSummary[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { if (!user) { setLoading(false); return }; getJson<{ orders: OrderSummary[] }>('/orders/orders?limit=20').then((data) => setOrders(data.orders || [])).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)) }, [user])
  if (!user) return <SimpleAccountPage title="Your orders are private." text="Sign in to view order history and tracking." link="/login" linkText="Sign in" />
  if (loading) return <main className="section empty-page"><h1>Loading your orders...</h1></main>
  return <main className="orders-page section"><div className="catalog-heading"><div><span className="eyebrow">Your shopping history</span><h1>Orders</h1></div></div>{error && <div className="api-notice">{error}</div>}{orders.length ? <div className="orders-list">{orders.map((order) => <Link className="order-row" to={`/orders/${order._id}`} key={order._id}><div><span className="eyebrow">Order placed</span><strong>{new Date(order.createdAt).toLocaleDateString('en-IN')}</strong><small>{order.items?.length || 0} items</small></div><div><span className={`status status--${order.orderStatus}`}>{order.orderStatus}</span><strong>{formatPrice(order.finalAmount)}</strong></div><b>↗</b></Link>)}</div> : <div className="empty-page"><h1>No orders yet.</h1><p>Your next favourite is waiting to be discovered.</p><Link className="primary-button" to="/products">Explore products</Link></div>}</main>
}

type TrackingItem = { fulfillmentStatus?: string; trackingTimeline?: Array<{ event?: string; location?: string; remarks?: string; scannedAt?: string }> }
type TrackingResponse = { orderId: string; orderStatus: string; createdAt: string; items: TrackingItem[] }

export function OrderDetailPage() {
  const { user } = useAuth(); const { id = '' } = useParams(); const location = useLocation(); const isTracking = location.pathname.endsWith('/tracking')
  const [order, setOrder] = useState<OrderDetail | null>(null); const [tracking, setTracking] = useState<TrackingResponse | null>(null); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState('')
  const refresh = () => getJson<OrderDetail>(`/orders/orders/${id}`).then(setOrder)
  useEffect(() => { if (!user) { setLoading(false); return }; const request = isTracking ? getJson<TrackingResponse>(`/orders/orders/${id}/track`).then(setTracking) : refresh(); request.catch((error: Error) => setMessage(error.message)).finally(() => setLoading(false)) }, [id, isTracking, user])
  const action = async (name: string, path: string, payload?: unknown) => { setBusy(name); setMessage(''); try { await sendJson(path, 'POST', payload); await refresh(); setMessage(`${name} request completed.`) } catch (error) { setMessage((error as Error).message) } finally { setBusy('') } }
  const downloadInvoice = async () => { setBusy('invoice'); setMessage(''); try { const blob = await getBlob(`/orders/orders/${id}/invoice`); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `smartcart-invoice-${id}.pdf`; anchor.click(); URL.revokeObjectURL(url); setMessage('Invoice download started.') } catch (error) { setMessage((error as Error).message) } finally { setBusy('') } }
  if (!user) return <SimpleAccountPage title="Sign in to view this order." text="Your order details are protected." link="/login" linkText="Sign in" />
  if (loading) return <main className="section empty-page"><h1>Loading order...</h1></main>
  if (isTracking && tracking) return <main className="order-detail-page section"><span className="eyebrow">Live order tracking</span><h1>Your delivery journey.</h1><p className="order-number">Order #{tracking.orderId}</p><div className="timeline-card">{tracking.items?.map((item, index) => <div className="tracking-item" key={index}><span className={`status status--${item.fulfillmentStatus}`}>{item.fulfillmentStatus || 'pending'}</span>{item.trackingTimeline?.map((event, eventIndex) => <div className="timeline-event" key={eventIndex}><span className="timeline-dot" /><div><strong>{event.event || 'Shipment update'}</strong><small>{event.location || 'SmartCart logistics'} · {event.scannedAt ? new Date(event.scannedAt).toLocaleString('en-IN') : ''}</small>{event.remarks && <p>{event.remarks}</p>}</div></div>)}</div>)}</div><Link className="back-link" to={`/orders/${tracking.orderId}`}>← Back to order</Link></main>
  if (!order) return <main className="section empty-page"><h1>Order unavailable</h1><p>{message}</p></main>
  const canCancel = ['pending', 'processing', 'confirmed'].includes(order.orderStatus)
  return <main className="order-detail-page section"><span className="eyebrow">Order confirmation</span><h1>{order.orderStatus === 'cancelled' ? 'This order was cancelled.' : 'Thank you for your order.'}</h1><p className="order-number">Order #{order._id}</p>{message && <div className="api-notice">{message}</div>}<div className="order-detail-card"><div className="order-status-banner"><span className={`status status--${order.orderStatus}`}>{order.orderStatus}</span><strong>{formatPrice(order.finalAmount)}</strong></div>{order.items?.map((item, index) => <div className="order-item" key={item._id || index}><div><strong>{item.product?.name || 'Product'}</strong><small>Quantity: {item.quantity || 1} · {item.fulfillmentStatus || 'processing'}</small>{item.returnStatus && item.returnStatus !== 'none' && <small>Return: {item.returnStatus}</small>}{item.refundStatus && item.refundStatus !== 'none' && <small>Refund: {item.refundStatus}</small>}</div><b>{formatPrice(item.lineTotal)}</b><div className="order-item-actions">{item.returnStatus === 'none' && item.fulfillmentStatus === 'delivered' && <button className="link-button" disabled={!!busy} onClick={() => action('Return', `/orders/orders/${id}/return`, { itemId: item._id, reason: 'Changed my mind' })}>Return</button>}{item.returnStatus === 'approved' && item.refundStatus === 'none' && <button className="link-button" disabled={!!busy} onClick={() => action('Refund', `/orders/orders/${id}/refund`, { itemId: item._id, reason: 'Refund requested by customer' })}>Refund</button>}</div></div>)}<div className="order-actions"><Link className="primary-button" to="/orders">View all orders</Link><Link className="ghost-dark-button" to={`/orders/${order._id}/tracking`}>Track order</Link><button className="ghost-dark-button" disabled={!!busy} onClick={downloadInvoice}>{busy === 'invoice' ? 'Preparing...' : 'Download invoice'}</button>{canCancel && <button className="link-button" disabled={!!busy} onClick={() => action('Cancellation', `/orders/orders/${id}/cancel`)}>Cancel order</button>}</div></div></main>
}
