import { Check, X } from 'lucide-react'
import { formatPrice } from '../../utils/formatters'

type Action = (key: string, path: string, method?: string, payload?: unknown) => Promise<void>
type PageProps = { page: number; pageSize: number; onPageChange: (page: number) => void }
type User = { _id: string; fullname?: string; username?: string; email?: string; role?: string; phone?: string; isActive?: boolean; isApproved?: boolean; createdAt?: string }
type Product = { _id: string; name: string; approvalStatus?: string; ratings?: number; sold?: number; seller?: { fullname?: string; email?: string }; category?: { name?: string } }
type Category = { _id: string; name: string; slug?: string; status?: string; parent?: { name?: string }; proposedBy?: { fullname?: string; email?: string } }

const statusLabel = (value?: string) => (value || 'pending').replace(/_/g, ' ')
const dateLabel = (value?: string) => value ? new Date(value).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }) : '-'

export function AdminResourcePagination({ page, pageSize, hasNext, onPageChange }: PageProps & { hasNext: boolean }) {
  return <div className="admin-pagination"><button className="outline-button" disabled={page === 1} onClick={() => onPageChange(Math.max(1, page - 1))}>Previous</button><span>Page <strong>{page}</strong>  -  {pageSize} per page</span><button className="outline-button" disabled={!hasNext} onClick={() => onPageChange(page + 1)}>Next</button></div>
}

export function AdminProductsView({ products, busy, onAction, onViewDetails, page, pageSize, onPageChange }: { products: Product[]; busy: string; onAction: Action; onViewDetails: (id: string) => void } & PageProps) {
  return <section className="admin-table-panel"><div className="admin-panel__heading"><div><span className="eyebrow">Catalog control</span><h2>Product moderation</h2></div><span className="admin-count">{products.length} loaded</span></div><div className="admin-table-wrap"><table><thead><tr><th>Product</th><th>Seller</th><th>Category</th><th>Status</th><th className="align-right">Actions</th></tr></thead><tbody>{products.map((product) => <tr key={product._id}><td><button className="admin-table-link" onClick={() => onViewDetails(product._id)}><strong>{product.name}</strong><small>{product.sold || 0} sold  -  {Number(product.ratings || 0).toFixed(1)} rating</small></button></td><td>{product.seller?.fullname || product.seller?.email || '-'}</td><td>{product.category?.name || '-'}</td><td><span className={'admin-status admin-status--' + (product.approvalStatus || 'pending')}>{statusLabel(product.approvalStatus)}</span></td><td className="align-right admin-actions"><button className="small-action" onClick={() => onViewDetails(product._id)}>View</button>{product.approvalStatus === 'pending' && <><button className="icon-action icon-action--good" disabled={busy === product._id} onClick={() => void onAction(product._id, '/products/products/' + product._id + '/approve')} title="Approve"><Check size={15} /></button><button className="icon-action icon-action--bad" disabled={busy === product._id} onClick={() => void onAction(product._id, '/products/products/' + product._id + '/reject')} title="Reject"><X size={15} /></button></>}</td></tr>)}</tbody></table>{!products.length && <div className="admin-empty">No products found.</div>}</div><AdminResourcePagination page={page} pageSize={pageSize} hasNext={products.length === pageSize} onPageChange={onPageChange} /></section>
}

export function AdminCategoriesView({ categories, busy, onAction, onViewDetails, page, pageSize, onPageChange }: { categories: Category[]; busy: string; onAction: Action; onViewDetails: (id: string) => void } & PageProps) {
  return <section className="admin-table-panel"><div className="admin-panel__heading"><div><span className="eyebrow">Taxonomy control</span><h2>Category moderation</h2></div><span className="admin-count">{categories.length} loaded</span></div><div className="admin-table-wrap"><table><thead><tr><th>Category</th><th>Parent</th><th>Proposed by</th><th>Status</th><th className="align-right">Actions</th></tr></thead><tbody>{categories.map((category) => <tr key={category._id}><td><button className="admin-table-link" onClick={() => onViewDetails(category._id)}><strong>{category.name}</strong><small>{category.slug || '-'}</small></button></td><td>{category.parent?.name || 'Top level'}</td><td>{category.proposedBy?.fullname || category.proposedBy?.email || 'Admin'}</td><td><span className={'admin-status admin-status--' + (category.status || 'pending')}>{statusLabel(category.status)}</span></td><td className="align-right admin-actions"><button className="small-action" onClick={() => onViewDetails(category._id)}>View</button>{category.status === 'pending' && <><button className="small-action" disabled={busy === category._id} onClick={() => void onAction(category._id, '/categories/admin/approve/' + category._id, 'PATCH')}>Approve</button><button className="small-action small-action--danger" disabled={busy === category._id} onClick={() => void onAction(category._id, '/categories/admin/reject/' + category._id, 'PATCH', { reason: 'Does not meet catalog standards' })}>Reject</button></>}</td></tr>)}</tbody></table>{!categories.length && <div className="admin-empty">No categories found.</div>}</div><AdminResourcePagination page={page} pageSize={pageSize} hasNext={categories.length === pageSize} onPageChange={onPageChange} /></section>
}

export function AdminUsersView({ title, users, busy, onAction, onViewDetails, sellerMode = false, page, pageSize, onPageChange }: { title: string; users: User[]; busy: string; onAction: Action; onViewDetails: (id: string) => void; sellerMode?: boolean } & PageProps) {
  return <section className="admin-table-panel"><div className="admin-panel__heading"><div><span className="eyebrow">People</span><h2>{title}</h2></div><span className="admin-count">{users.length} loaded</span></div><div className="admin-table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Joined</th><th>Status</th><th className="align-right">Actions</th></tr></thead><tbody>{users.map((account) => <tr key={account._id}><td><button className="admin-table-link" onClick={() => onViewDetails(account._id)}><strong>{account.fullname || account.username || 'Unnamed account'}</strong><small>@{account.username || '-'}</small></button></td><td>{account.email || '-'}</td><td>{dateLabel(account.createdAt)}</td><td><span className={'admin-status ' + (account.isActive === false ? 'admin-status--cancelled' : 'admin-status--approved')}>{account.isActive === false ? 'inactive' : sellerMode && account.isApproved === false ? 'pending' : 'active'}</span></td><td className="align-right admin-actions"><button className="small-action" onClick={() => onViewDetails(account._id)}>View</button>{sellerMode && account.isApproved === false && <button className="small-action" disabled={busy === account._id} onClick={() => void onAction(account._id, '/users/admin/sellers/' + account._id + '/approve')}>Approve</button>}{sellerMode && <button className="small-action small-action--danger" disabled={busy === account._id} onClick={() => void onAction(account._id, '/users/admin/sellers/' + account._id + '/' + (account.isActive === false ? 'unsuspend' : 'suspend'))}>{account.isActive === false ? 'Unsuspend' : 'Suspend'}</button>}{account.isActive !== false ? <button className="small-action small-action--danger" disabled={busy === account._id} onClick={() => void onAction(account._id, '/users/admin/users/' + account._id + '/deactivate')}>Deactivate</button> : <button className="small-action" disabled={busy === account._id} onClick={() => void onAction(account._id, '/users/admin/users/' + account._id + '/reactivate')}>Reactivate</button>}</td></tr>)}</tbody></table>{!users.length && <div className="admin-empty">No accounts found.</div>}</div><AdminResourcePagination page={page} pageSize={pageSize} hasNext={users.length === pageSize} onPageChange={onPageChange} /></section>
}

const valueText = (value: unknown) => value === undefined || value === null || value === '' ? '-' : String(value)
function DetailGrid({ rows }: { rows: Array<[string, unknown]> }) { return <div className="admin-resource-grid">{rows.map(([label, value]) => <div key={label}><span>{label}</span><strong>{valueText(value)}</strong></div>)}</div> }

export function AdminResourceDetailsDrawer({ type, data, onClose }: { type: 'product' | 'category' | 'customer' | 'seller'; data: any; onClose: () => void }) {
  const title = `${type === 'product' ? data.name : type === 'category' ? data.name : data.fullname || data.username || 'Account details'}  -  ${data._id || 'ID unavailable'}`
  const image = type === 'product' ? data.coverImage?.url || data.images?.[0]?.url : undefined
  const rows: Array<[string, unknown]> = type === 'product'
    ? [['Brand', data.brand], ['Slug', data.slug], ['Price', formatPrice(Number(data.price || 0))], ['Final price', formatPrice(Number(data.finalPrice || data.price || 0))], ['Discount', data.discountPercentage ? `${data.discountPercentage}%` : 'None'], ['Stock', data.stock], ['Sold', data.sold], ['Rating', data.ratings], ['Reviews', data.reviews ?? data.numberOfReviews], ['Approval', statusLabel(data.approvalStatus)], ['Rejection reason', data.rejectionReason], ['Active', data.isActive === false ? 'No' : 'Yes'], ['Featured', data.featured ? 'Yes' : 'No'], ['Archived', data.isArchived ? 'Yes' : 'No'], ['Images', Array.isArray(data.images) ? data.images.length : 0], ['Category', data.category?.name], ['Subcategory', data.subCategory?.name], ['Seller', data.seller?.fullname || data.seller?.email], ['Badges', Array.isArray(data.badges) ? data.badges.join(', ') : undefined], ['Tags', Array.isArray(data.tags) ? data.tags.join(', ') : undefined], ['Variants', Array.isArray(data.variants) ? data.variants.map((variant: any) => variant.label).join(', ') : undefined], ['Flash sale', data.flashSale?.isActive ? `${data.flashSale.discountPercentage || 0}% until ${dateLabel(data.flashSale.end)}` : 'None'], ['Created', dateLabel(data.createdAt)], ['Updated', dateLabel(data.updatedAt)]]
    : type === 'category'
      ? [['Slug', data.slug], ['Parent', data.parent?.name || 'Top level'], ['Level', data.level], ['Products', data.productCount ?? data.productsCount], ['Status', statusLabel(data.status)], ['Active', data.isActive === false ? 'No' : 'Yes'], ['Featured', data.isFeatured ? 'Yes' : 'No'], ['Deleted', data.isDeleted ? 'Yes' : 'No'], ['Display order', data.order], ['Proposed by', data.proposedBy?.fullname || data.proposedBy?.email], ['Tagline', data.tagline], ['Tags', Array.isArray(data.tags) ? data.tags.join(', ') : undefined], ['SEO title', data.metaTitle], ['SEO description', data.metaDescription], ['SEO keywords', data.metaKeywords], ['Created', dateLabel(data.createdAt)], ['Updated', dateLabel(data.updatedAt)]]
      : [['Role', data.role], ['Email', data.email], ['Phone', data.phone], ['Status', data.isActive === false ? 'Inactive' : 'Active'], ['Email verified', data.isEmailVerified ? 'Yes' : 'No'], ['Phone verified', data.isPhoneVerified ? 'Yes' : 'No'], ['Joined', dateLabel(data.createdAt)], ['Updated', dateLabel(data.updatedAt)], ['Orders', data.orderCount], ['Delivered', data.deliveredOrders], ['Cancelled', data.cancelledOrders], ['Total spent', formatPrice(Number(data.totalSpent || 0))], ['Products listed', data.productCount], ['Last order', data.lastOrder ? `${statusLabel(data.lastOrder.orderStatus)}  -  ${dateLabel(data.lastOrder.createdAt)}` : undefined], ['Username', data.username], ['Permissions', Array.isArray(data.permissions) ? data.permissions.join(', ') : undefined]]
  return <div className="admin-drawer-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><aside className="admin-order-drawer admin-resource-drawer" role="dialog" aria-modal="true" aria-label={`${title} details`}><div className="admin-order-drawer__header"><div><span className="eyebrow">{type} details</span><h2>{title}</h2></div><button className="icon-action" onClick={onClose} aria-label="Close details"><X size={20} /></button></div>{image && <div className="admin-resource-image"><img src={image} alt={title} /></div>}<DetailGrid rows={rows} />{data.description && <section className="admin-drawer-section"><span className="eyebrow">Description</span><p className="admin-resource-copy">{data.description}</p></section>}{data.sellerProfile && <section className="admin-drawer-section"><span className="eyebrow">Seller profile</span><DetailGrid rows={Object.entries(data.sellerProfile).filter(([key]) => !['documents', 'bankDetails'].includes(key)).slice(0, 8) as Array<[string, unknown]>} /></section>}{data.addresses?.length > 0 && <section className="admin-drawer-section"><span className="eyebrow">Addresses</span>{data.addresses.map((address: any, index: number) => <p className="admin-resource-copy" key={index}>{[address.label, address.addressLine, address.city, address.state, address.pincode].filter(Boolean).join('  -  ')}</p>)}</section>}</aside></div>
}




